apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2  # Ensure this matches your available StorageClass
  resources:
    requests:
      storage: 1Gi
