apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse-interface
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warehouse-interface
  template:
    metadata:
      labels:
        app: warehouse-interface
    spec:
      containers:
      - name: warehouse-interface
        image: gpickers/warehouse-interface