FROM python:3.9

WORKDIR /app

COPY . .

RUN pip install requests \
                opentelemetry-api \
                opentelemetry-sdk \
                opentelemetry-exporter-otlp \
                opentelemetry-instrumentation-requests

CMD ["python", "warehouse-interface.py"]