# Use an official Python runtime as the base image
FROM python:3.9

# Set metadata labels for best practices
LABEL authors="George Pickers,George Boddey"
LABEL org.label-schema.vendor="Coralogix"
LABEL org.label-schema.name="Tracey Reloaded - Stock Controller"
LABEL org.label-schema.description="Stock Controller for Tracey Reloaded"
LABEL org.label-schema.version="1.0"
LABEL org.label-schema.url="https://github.com/georgep1ckers/tracey-reloaded"
LABEL org.label-schema.vcs-url="https://github.com/georgep1ckers/tracey-reloaded"
LABEL org.label-schema.schema-version="1.0"
# Set the working directory inside the container
WORKDIR /app

# Copy the current directory contents into the container
COPY . .

# Install the required packages
RUN pip install -r requirements.txt

# Make port 8081 available to the world outside this container
EXPOSE 8081

# Define the command to run the app using CMD
CMD ["python", "stock-controller.py"]