# Use an official Python runtime as the base image
FROM python:3.9

# Set the working directory inside the container
WORKDIR /app

# Copy the current directory contents into the container
COPY . .

# Install the required packages
RUN pip install -r requirements.txt

# Make port 8081 available to the world outside this container
EXPOSE 8081

# Define the command to run the app using CMD
CMD ["python", "stock-controller.py"]