FROM python:3.9

WORKDIR /app

COPY . .

RUN pip install flask \
                opentelemetry-api \
                opentelemetry-sdk \
                opentelemetry-exporter-otlp \
                opentelemetry-instrumentation-flask \
                psycopg2 \
                opentelemetry-instrumentation-psycopg2

CMD ["python", "order-processor.py"]