name: Build and Push Docker Images

on:
  push:
    branches:
      - main
      - gh-actions
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image-folder:
          - order-processor
          - stock-controller
          - warehouse-interface

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./tracey-reloaded/${{ matrix.image-folder }}
          tags: ${{ github.repository_owner }}/${{ github.repository_name }}-${{ matrix.image-folder }}:latest
          labels: ${{ steps.meta.outputs.labels}}
          push: true

